
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname="Debian-Node02"  
  config.vm.box_check_update = false

   #config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "public_network", bridge: "Killer E2600 Gigabit Ethernet Controller", ip: "192.168.0.90"
  
   config.vm.synced_folder ".", "/vagrant", disabled: false
   config.vm.provider "virtualbox" do |vb|
    #   vb.gui = true
    vb.memory = "2048"
   end

   config.vm.provision "shell", path:"provision.sh"
   #config.vm.provision "shell", inline: <<-SHELL
   #SHELL
end
