- name: Instalar o MySQL
  hosts: bd01
  become: true
  vars_files:
  - vars/main.yml
 
  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      become: true
    - name: Instalar o pacote MySQL Server
      apt:
        name: ["default-mysql-server","python3-mysqldb","htop"]
        state: present
      become: true
    - name: Inicializando o Mysql
      service:
        name: mysqld
        state: started
        enabled: true
    - name: Criar usuário e conceder privilégios
      mysql_user:
        name: renato
        password: renato
        priv: "*.*:ALL"
        host: 0.0.0.0
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Cria banco de dados
      mysql_db:
        name: my-database 
        state: present 
          
