
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname="db01"  
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: "192.168.0.81"
  config.vm.network "forwarded_port", guest: 22, host: 22, host_ip: "192.168.0.81" 

  config.vm.network "public_network", bridge: "Killer E2600 Gigabit Ethernet Controller", ip: "192.168.0.81"
  # config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
   end
   config.vm.provision "shell", inline: <<-SHELL
   #  apt install mariadb -y
      hostnamectl set-hostname DB01  
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCtPz8VFpCwBfXS25LOPKhO5ApMbUsc5GquZ5+h79FKMX6MLDAmlUfcxMqMYwLROJ+hv3Sl4JUM4dfwYEH+urinSCfmlrUdW06j9rtLoMu9Be0N8A4kAtFEwhTaSRikas6jNEiB0PGSNQCl4rGZ7L3PdjQwlbhmmi2CyQvWMbZhYtFEs7v6hsL8r3ox7YcA3yj0dpyTgnX35WK7R5kI1Z/myJTW6S2ReZQSmlqUKX4ysjWES8pShHzwkYZYiNR9Y6e4mdhn/tlrKUsdLUFOjHzWBRE4kgs65eWvmiLaCPZAWn3SibpCfNyu/3WoS5GqYXTiwlc3Afs6kKB8XkH/CuElqaztA6uE2AvtEV3WMF8GiZcFyv6psbZkyxI75SNpiypXgkFyCyLi6JA/MQnE2jSEAzJ3I3GmGFcjb28tWmhAYhV6+o8uNeuMcCdMXcDwPEKD3mw0C0EPYl0lSjUE9sDcTeGmWKyNMn4iMZggkgG2K252WQSsqvEruI/sHi7L18= root@debian-node" > /root/.ssh/authorized_keys
   #apt install htop -y
     #apt install net-tools -y
   SHELL
end
#vaconfig.vm.provision "shell", path:"provision.sh"